query GetPoolsLive($first: Int = 100, $skip: Int = 0, $containsId: [Int])
@live {
  # this one is coming from compound-v3
  pools(
    first: $first
    skip: $skip
    orderBy: volumeUSD
    orderDirection: desc
    where: { totalValueLockedUSD_gt: 10000 }
  ) {
    id
    token0 {
      id
      symbol
      name
    }
    token1 {
      id
      symbol
      name
    }
    poolDayData(first: 1, orderBy: date, orderDirection: desc) {
      id
      volumeUSD
      date
    }
    token0Price
    token1Price
    volumeUSD
  }

  # this one is coming from compound-v2
  pairs(first: $first, skip: $skip, orderBy: volumeUSD, orderDirection: desc) {
    id
    token0 {
      id
      name
    }
    token1 {
      id
      name
    }
    token0Price
    token1Price
  }
}
