name: solidity-deploy
run-name: ${{ github.actor }} solidity deploy
on:
  push:
    branches: [main]
    paths:
      - "solidity/**"
      - ".github/workflows/**"
jobs:
  test-contracts:
    runs-on: ubuntu-latest
    env:
      CODEBUCKET_ENV: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_DEV }}" > ".env.$CODEBUCKET_ENV"
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn run dev-test
